### ISSUE TITLE
Autosmelt?

### ISSUE THREAD

**Issue by Blatts12** [Gnomorian/gnom-gnom-utils#35]
When I had GGUtils TCon pickaxe have autosmelt enchant

**Comment by Blatts12** [comment]
any news?

**Comment by Unrelentless** [comment]
Hey man.

I'm will be back on trying it out on Monday.
But I've tried replicating the error by installing just GGUtils and TC but
couldn't get the same thing you were getting.

**Comment by Blatts12** [comment]
I also have a Iguanas Tinker Tweaks and ExtraTiC

**Comment by Blatts12** [comment]
Okay, when I add GGUtils to ResonantRise 3 I have this same problem. And I think it's fault ExtraTiC.

**Comment by DaedalusGame** [comment]
Running into the same problem and changing the Enchantment ID doesn't fix the issue

I took a peek at the relevant code; you check the enchantment level of Icarus, but you only check if the enchantment list is not null on the Prosperity enchantment blockbreak event?

Testing confirms that putting any enchantment on an axe, e.g Sharpness I, will bug the axe and it will autosmelt cut logs into charcoal (most of the time it doesn't drop anything, appears to be really buggy)

**Comment by Gnomorian** [comment]
Hmm, maybe it's a merge issue, worked perfectly when I made the demo video. I'll see about fixing it when I get home from work.

**Comment by Gnomorian** [comment]
As in, when we merged git branches, screwing things up, that happens allot

**Comment by Gnomorian** [comment]
ok, fixed the bug in the 0.1.1.6 version, or atleast its working fine for me. give it a go.

**Comment by Gnomorian** [comment]
iv not had issues with the patch, and no one has replied to state continued problems, so im closing the issue.
